using System;
using System.ComponentModel.DataAnnotations;

namespace Ecommerce.Models
{
    /// <summary>
    /// Represents a temporary data transfer object blueprint used exclusively for managing account signup submissions.
    /// Decorates validation attributes to verify form fields are error-free before generating a persistent database member.
    /// </summary>
    public class RegistrationViewModel
    {
        /// <summary>
        /// Gets or sets the custom public profile identifier handle requested by the visitor.
        /// Constrained strictly to alphanumeric characters via regular expressions with a maximum ceiling cap of 25 parameters.
        /// </summary>
        [RegularExpression("^[a-zA-Z0-9]+$", ErrorMessage = "Username must be alphanumeric.")]
        [StringLength(25)]
        public required string Username { get; set; }

        /// <summary>
        /// Gets or sets the primary digital messaging communication contact handle submitted during the signup phase.
        /// Configured with specific metadata flags to optimize browser keyboard layouts for email input collection workflows.
        /// </summary>
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Invalid email address format.")]
        public required string Email { get; set; }

        /// <summary>
        /// Gets or sets the raw, unencrypted secret key verification string generated by the new user account owner.
        /// Restricted to length parameters requiring between 6 and 50 characters, and automatically masked on-screen.
        /// </summary>
        [StringLength(50, MinimumLength = 6, ErrorMessage = "Your password must be between 6 and 50 characters long.")]
        [DataType(DataType.Password)]
        public required string Password { get; set; }

        /// <summary>
        /// Gets or sets the secondary verification password field mapping to protect against accidental user typography mistakes.
        /// Instructs the compiler to execute property validation comparisons ensuring exact string character parity with the primary password field.
        /// </summary>
        [Compare(nameof(Password), ErrorMessage = "The password and confirmation password do not match.")]
        [DataType(DataType.Password)]
        public required string ConfirmPassword { get; set; }

        /// <summary>
        /// Gets or sets the documented user date of birth milestone chronologically tracking calendar date boundaries.
        /// Instructs front-end templates to automatically surface native browser calendar date picker pop-up window utilities.
        /// </summary>
        [DataType(DataType.Date)]
        public DateOnly DateOfBirth { get; set; }
    }
}
